### ISSUE TITLE
Can not install 

### ISSUE THREAD

**Issue by TheCrey** [james-fry/hassio-addons#10]
Hi,
while I try to install it I get the following error message:

`18-01-23 20:32:52 INFO (SyncWorker_7) [hassio.docker.addon] Start build f3248fb7/amd64-addon-dasher:0.2
18-01-23 20:32:52 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 410, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 325, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 93, in impl
    return (yield from handler(request))
  File "/usr/lib/python3.6/site-packages/hassio/api/utils.py", line 33, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/addons/addon.py", line 524, in install
    if not await self.instance.install(self.last_version):
  File "/usr/lib/python3.6/site-packages/hassio/docker/utils.py", line 18, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/docker/addon.py", line 263, in _install
    return self._build(tag)
  File "/usr/lib/python3.6/site-packages/hassio/docker/addon.py", line 276, in _build
    image = self._docker.images.build(**build_env.get_docker_args(tag))
  File "/usr/lib/python3.6/site-packages/docker/models/images.py", line 179, in build
    raise BuildError(chunk['error'])
docker.errors.BuildError: Please provide a source image with `from` prior to commit`

Its a genereic Ubuntu Server:
Its the first thing I tried to install after a clean setup. 
Current version | 0.61.1

`
Hostname | ubuntuhassio
-- | --
Type | generic
OS | GNU/Linux
Host Control version | 0.3
Latest available version | 0.3
`

Any idea what this could be ? 
Installing on RPI3 works fine. (with the image of course) 

Regards

**Comment by lukasrininsland** [comment]
Hi, I have a similar problem. When I click install, it seems to work for a few minutes, but stops without displaying an error message and you can click install again.
I cannot install all four of your extensions.

I'm using a Raspberry Pi 3B + and can install all other extensions.

![2020-01-26 13_13_10-Home Assistant](https://user-images.githubusercontent.com/51824765/73135037-0c7ead80-403e-11ea-9a91-f96ce3ef7c47.png)

**Comment by Michele184** [comment]
Ciao, io non riesco ad installare.
Tramite "Configurator" ho creato il file rtl2mqtt.sh da nuovo e ho incollato il contenuto (raw) all'interno. Cntinuo ad avere log: 
/bin/ash: /rtl2mqtt.sh: not found
Dove sbaglio? Cosa posso fare?

**Comment by LennyPenny** [comment]
I'm getting the same as @Michele184, the file exists and is executable
![image](https://user-images.githubusercontent.com/4027243/78456949-317b4680-76a7-11ea-8960-9bfc8ab8100c.png)

**Comment by DavidREWorthington** [comment]
I have the same problem - have you found a solution?

**Comment by cristianchiribes** [comment]
Here too! ...

**Comment by james-fry** [comment]
Hi All, As th author of the addon I need to apologise that I am not able to assist you to debug this.
The addon is old and hassio requirements have changed since I created it (not sure if this impacts or not), but more importantly the 433mhz device I designed the addon to use with (currentcost power meter) has broken, so I am no longer able to even use the addon :(

My suggestion is for a capable user to fork the addon and continue maintenance.
