### ISSUE TITLE
dasher doesn't run

### ISSUE THREAD

**Issue by host-felice** [james-fry/hassio-addons#12]
I tried to install the dasher plug-in for hass.io 0.64.6 but when I start it, I get this log:

starting version 3.2.4
> dasher@1.4.1 start /root/dasher
> node app.js
warning: SIOCGIFADDR: en0: No such device - this may not actually work
Error: SIOCGIFHWADDR: No such device
    at new PcapSession (/root/dasher/node_modules/pcap/pcap.js:49:39)
    at Object.exports.createSession (/root/dasher/node_modules/pcap/pcap.js:123:12)
    at create_session (/root/dasher/node_modules/node-dash-button/index.js:24:28)
    at register (/root/dasher/node_modules/node-dash-button/index.js:47:24)
    at new DasherButton (/root/dasher/lib/dasher.js:14:21)
    at Object.<anonymous> (/root/dasher/app.js:8:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
Failed to create pcap session: couldn't find devices to listen on.
Try running with elevated privileges via 'sudo'
/root/dasher/node_modules/node-dash-button/index.js:28
        throw new Error('Error: No devices to listen');
        ^
Error: Error: No devices to listen
    at create_session (/root/dasher/node_modules/node-dash-button/index.js:28:15)
    at register (/root/dasher/node_modules/node-dash-button/index.js:47:24)
    at new DasherButton (/root/dasher/lib/dasher.js:14:21)
    at Object.<anonymous> (/root/dasher/app.js:8:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dasher@1.4.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dasher@1.4.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-24T20_22_29_339Z-debug.log

**Comment by host-felice** [comment]
my mistake in the config.json file
