### ISSUE TITLE
Cannot Install in Hassio 0.54 Pi2

### ISSUE THREAD

**Issue by derechtedude** [james-fry/hassio-addons#5]
addition of https://github.com/james-fry/hassio-addons as repository
but install button does not do anything
It worked on a Pi Zero though a couple of days ago

**Comment by byransays** [comment]
Same here with a Pi2. 

here is the supervisor log error:
17-09-30 18:42:08 INFO (SyncWorker_15) [hassio.dock.addon] Start build f3248fb7/armhf-addon-dasher:0.1
17-09-30 18:42:09 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/util.py", line 31, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/api/addons.py", line 171, in install
    addon.install(version=version), loop=self.loop)
  File "/usr/lib/python3.6/site-packages/hassio/addons/addon.py", line 443, in install
    if not await self.docker.install(version):
  File "/usr/lib/python3.6/site-packages/hassio/dock/util.py", line 18, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 196, in _install
    return self._build(tag)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 209, in _build
    image = self.docker.images.build(**build_env.get_docker_args(tag))
  File "/usr/lib/python3.6/site-packages/docker/models/images.py", line 175, in build
    raise BuildError(chunk['error'])
docker.errors.BuildError: invalid reference format: repository name must be lowercase

**Comment by james-fry** [comment]
Thanks for reporting the issue.
I can confirm that I can reproduce this issue on x86/ubuntu also.
Investigating....

**Comment by james-fry** [comment]
Please can you update docker to latest version (or update hassio RPi OS) and try again.
Working for me...

**Comment by james-fry** [comment]
Reported as fixed:
https://community.home-assistant.io/t/repository-amazon-dash-button-support-dasher/23938/10
