### ISSUE TITLE
Can't install this addon

### ISSUE THREAD

**Issue by bonanitech** [james-fry/hassio-addons#7]
I'm seeing these error messages in the log when trying to install this addon. My hass.io is running on Ubuntu Server 17.10.

17-11-21 19:46:57 INFO (MainThread) [hassio.addons.addon] Create Home-Assistant addon data folder /data/addons/data/f3248fb7_dasher
17-11-21 19:46:57 INFO (SyncWorker_8) [hassio.dock.addon] Start build f3248fb7/amd64-addon-dasher:0.2
17-11-21 19:46:57 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 416, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 323, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/util.py", line 31, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/addons/addon.py", line 474, in install
    if not await self.docker.install(self.last_version):
  File "/usr/lib/python3.6/site-packages/hassio/dock/util.py", line 18, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 219, in _install
    return self._build(tag)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 232, in _build
    image = self.docker.images.build(**build_env.get_docker_args(tag))
  File "/usr/lib/python3.6/site-packages/docker/models/images.py", line 175, in build
    raise BuildError(chunk['error'])
docker.errors.BuildError: Please provide a source image with `from` prior to commit

How can I fix this problem?

Thanks.

**Comment by bonanitech** [comment]
I was using the docker.io package, now with docker-ce everything is working fine.
