### ISSUE TITLE
Hassio failed to bouild add-on

### ISSUE THREAD

**Issue by nsotnikov** [james-fry/hassio-addons#8]
Tried to start the addon on Hassio v0.58.1 -  RPi 3
Got following error (Log from **resin_supervisor**)

17-12-03 17:14:52 INFO (SyncWorker_2) [hassio.dock.addon] Start build f3248fb7/armhf-addon-dasher:0.2
17-12-03 17:15:35 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 416, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 323, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/hassio/api/util.py", line 31, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/addons/addon.py", line 474, in install
    if not await self.docker.install(self.last_version):
  File "/usr/lib/python3.6/site-packages/hassio/dock/util.py", line 18, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 219, in _install
    return self._build(tag)
  File "/usr/lib/python3.6/site-packages/hassio/dock/addon.py", line 232, in _build
    image = self.docker.images.build(**build_env.get_docker_args(tag))
  File "/usr/lib/python3.6/site-packages/docker/models/images.py", line 179, in build
    raise BuildError(chunk['error'])
docker.errors.BuildError: The command '/bin/sh -c cd /root/dasher && npm install' returned a non-zero code: 1

**Comment by nsotnikov** [comment]
After flashing the new hassio on   #sdcard everything works fine.
